from tkinter import *
master = Tk()
Label(master, text='First Name').grid(row=0)
Label(master, text='Last Name').grid(row=1)
e1 = Entry(master)
e2 = Entry(master)
e1.grid(row=0,column=1)
e2.grid(row=1,column=1)
var1=intVar()
Checkbutton(master,text='Male', variable=var1).grid(row=0,sticky=W)
var2=IntVar()
CHECKBUTTON(master, text='female')
mainloop()